# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fluid.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='fluid.proto',
  package='rpc',
  syntax='proto3',
  serialized_options=b'Z\006.;main',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x66luid.proto\x12\x03rpc\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1d\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\xa3\x01\n\tQueryEdge\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12\x11\n\tpredicate\x18\x02 \x01(\t\x12\x0e\n\x06object\x18\x03 \x01(\t\x12)\n\x05\x66irst\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12(\n\x04last\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05\x63ount\x18\x06 \x01(\r\".\n\rQueryResponse\x12\x1d\n\x05\x65\x64ges\x18\x01 \x03(\x0b\x32\x0e.rpc.QueryEdge\"M\n\x0bNodeRequest\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\\\n\x0cNodeResponse\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12\x0c\n\x04node\x18\x02 \x01(\x0c\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"g\n\x11NodeStreamRequest\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12\x12\n\nproperties\x18\x02 \x01(\x0c\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x14\n\x12NodeStreamResponse\"\x8a\x01\n\x11\x45\x64geStreamRequest\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12\x11\n\tpredicate\x18\x02 \x01(\t\x12\x0e\n\x06object\x18\x03 \x01(\t\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nproperties\x18\x05 \x01(\x0c\"\x14\n\x12\x45\x64geStreamResponse2\xe6\x01\n\x05\x46luid\x12.\n\x05Query\x12\x11.rpc.QueryRequest\x1a\x12.rpc.QueryResponse\x12+\n\x04Node\x12\x10.rpc.NodeRequest\x1a\x11.rpc.NodeResponse\x12?\n\nEdgeStream\x12\x16.rpc.EdgeStreamRequest\x1a\x17.rpc.EdgeStreamResponse(\x01\x12?\n\nNodeStream\x12\x16.rpc.NodeStreamRequest\x1a\x17.rpc.NodeStreamResponse(\x01\x42\x08Z\x06.;mainb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_QUERYREQUEST = _descriptor.Descriptor(
  name='QueryRequest',
  full_name='rpc.QueryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='rpc.QueryRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=82,
)


_QUERYEDGE = _descriptor.Descriptor(
  name='QueryEdge',
  full_name='rpc.QueryEdge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='subject', full_name='rpc.QueryEdge.subject', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='predicate', full_name='rpc.QueryEdge.predicate', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='object', full_name='rpc.QueryEdge.object', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='first', full_name='rpc.QueryEdge.first', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last', full_name='rpc.QueryEdge.last', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='rpc.QueryEdge.count', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=248,
)


_QUERYRESPONSE = _descriptor.Descriptor(
  name='QueryResponse',
  full_name='rpc.QueryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='edges', full_name='rpc.QueryResponse.edges', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=296,
)


_NODEREQUEST = _descriptor.Descriptor(
  name='NodeRequest',
  full_name='rpc.NodeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='subject', full_name='rpc.NodeRequest.subject', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='rpc.NodeRequest.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=298,
  serialized_end=375,
)


_NODERESPONSE = _descriptor.Descriptor(
  name='NodeResponse',
  full_name='rpc.NodeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='subject', full_name='rpc.NodeResponse.subject', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node', full_name='rpc.NodeResponse.node', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='rpc.NodeResponse.timestamp', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=469,
)


_NODESTREAMREQUEST = _descriptor.Descriptor(
  name='NodeStreamRequest',
  full_name='rpc.NodeStreamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='subject', full_name='rpc.NodeStreamRequest.subject', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='properties', full_name='rpc.NodeStreamRequest.properties', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='rpc.NodeStreamRequest.timestamp', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=471,
  serialized_end=574,
)


_NODESTREAMRESPONSE = _descriptor.Descriptor(
  name='NodeStreamResponse',
  full_name='rpc.NodeStreamResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=576,
  serialized_end=596,
)


_EDGESTREAMREQUEST = _descriptor.Descriptor(
  name='EdgeStreamRequest',
  full_name='rpc.EdgeStreamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='subject', full_name='rpc.EdgeStreamRequest.subject', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='predicate', full_name='rpc.EdgeStreamRequest.predicate', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='object', full_name='rpc.EdgeStreamRequest.object', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='rpc.EdgeStreamRequest.timestamp', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='properties', full_name='rpc.EdgeStreamRequest.properties', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=599,
  serialized_end=737,
)


_EDGESTREAMRESPONSE = _descriptor.Descriptor(
  name='EdgeStreamResponse',
  full_name='rpc.EdgeStreamResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=739,
  serialized_end=759,
)

_QUERYEDGE.fields_by_name['first'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_QUERYEDGE.fields_by_name['last'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_QUERYRESPONSE.fields_by_name['edges'].message_type = _QUERYEDGE
_NODEREQUEST.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_NODERESPONSE.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_NODESTREAMREQUEST.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_EDGESTREAMREQUEST.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['QueryRequest'] = _QUERYREQUEST
DESCRIPTOR.message_types_by_name['QueryEdge'] = _QUERYEDGE
DESCRIPTOR.message_types_by_name['QueryResponse'] = _QUERYRESPONSE
DESCRIPTOR.message_types_by_name['NodeRequest'] = _NODEREQUEST
DESCRIPTOR.message_types_by_name['NodeResponse'] = _NODERESPONSE
DESCRIPTOR.message_types_by_name['NodeStreamRequest'] = _NODESTREAMREQUEST
DESCRIPTOR.message_types_by_name['NodeStreamResponse'] = _NODESTREAMRESPONSE
DESCRIPTOR.message_types_by_name['EdgeStreamRequest'] = _EDGESTREAMREQUEST
DESCRIPTOR.message_types_by_name['EdgeStreamResponse'] = _EDGESTREAMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryRequest = _reflection.GeneratedProtocolMessageType('QueryRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYREQUEST,
  '__module__' : 'fluid_pb2'
  # @@protoc_insertion_point(class_scope:rpc.QueryRequest)
  })
_sym_db.RegisterMessage(QueryRequest)

QueryEdge = _reflection.GeneratedProtocolMessageType('QueryEdge', (_message.Message,), {
  'DESCRIPTOR' : _QUERYEDGE,
  '__module__' : 'fluid_pb2'
  # @@protoc_insertion_point(class_scope:rpc.QueryEdge)
  })
_sym_db.RegisterMessage(QueryEdge)

QueryResponse = _reflection.GeneratedProtocolMessageType('QueryResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYRESPONSE,
  '__module__' : 'fluid_pb2'
  # @@protoc_insertion_point(class_scope:rpc.QueryResponse)
  })
_sym_db.RegisterMessage(QueryResponse)

NodeRequest = _reflection.GeneratedProtocolMessageType('NodeRequest', (_message.Message,), {
  'DESCRIPTOR' : _NODEREQUEST,
  '__module__' : 'fluid_pb2'
  # @@protoc_insertion_point(class_scope:rpc.NodeRequest)
  })
_sym_db.RegisterMessage(NodeRequest)

NodeResponse = _reflection.GeneratedProtocolMessageType('NodeResponse', (_message.Message,), {
  'DESCRIPTOR' : _NODERESPONSE,
  '__module__' : 'fluid_pb2'
  # @@protoc_insertion_point(class_scope:rpc.NodeResponse)
  })
_sym_db.RegisterMessage(NodeResponse)

NodeStreamRequest = _reflection.GeneratedProtocolMessageType('NodeStreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _NODESTREAMREQUEST,
  '__module__' : 'fluid_pb2'
  # @@protoc_insertion_point(class_scope:rpc.NodeStreamRequest)
  })
_sym_db.RegisterMessage(NodeStreamRequest)

NodeStreamResponse = _reflection.GeneratedProtocolMessageType('NodeStreamResponse', (_message.Message,), {
  'DESCRIPTOR' : _NODESTREAMRESPONSE,
  '__module__' : 'fluid_pb2'
  # @@protoc_insertion_point(class_scope:rpc.NodeStreamResponse)
  })
_sym_db.RegisterMessage(NodeStreamResponse)

EdgeStreamRequest = _reflection.GeneratedProtocolMessageType('EdgeStreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _EDGESTREAMREQUEST,
  '__module__' : 'fluid_pb2'
  # @@protoc_insertion_point(class_scope:rpc.EdgeStreamRequest)
  })
_sym_db.RegisterMessage(EdgeStreamRequest)

EdgeStreamResponse = _reflection.GeneratedProtocolMessageType('EdgeStreamResponse', (_message.Message,), {
  'DESCRIPTOR' : _EDGESTREAMRESPONSE,
  '__module__' : 'fluid_pb2'
  # @@protoc_insertion_point(class_scope:rpc.EdgeStreamResponse)
  })
_sym_db.RegisterMessage(EdgeStreamResponse)


DESCRIPTOR._options = None

_FLUID = _descriptor.ServiceDescriptor(
  name='Fluid',
  full_name='rpc.Fluid',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=762,
  serialized_end=992,
  methods=[
  _descriptor.MethodDescriptor(
    name='Query',
    full_name='rpc.Fluid.Query',
    index=0,
    containing_service=None,
    input_type=_QUERYREQUEST,
    output_type=_QUERYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Node',
    full_name='rpc.Fluid.Node',
    index=1,
    containing_service=None,
    input_type=_NODEREQUEST,
    output_type=_NODERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='EdgeStream',
    full_name='rpc.Fluid.EdgeStream',
    index=2,
    containing_service=None,
    input_type=_EDGESTREAMREQUEST,
    output_type=_EDGESTREAMRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='NodeStream',
    full_name='rpc.Fluid.NodeStream',
    index=3,
    containing_service=None,
    input_type=_NODESTREAMREQUEST,
    output_type=_NODESTREAMRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FLUID)

DESCRIPTOR.services_by_name['Fluid'] = _FLUID

# @@protoc_insertion_point(module_scope)
